version: 0.0
os: linux
files:
  - source: /ui/index.html
    destination: /var/www/html/
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - python /lambda/index.py
