version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - cd lambda  # Change directory to the Lambda function folder
      - pip install -r requirements.txt  # Install Python dependencies using pip
      - npm install  # Install JavaScript dependencies using npm (if applicable)

  pre_build:
    commands:
      - cd ui  # Change directory to the user interface folder
      - npm run build  # Build the user interface using npm (if applicable)

  build:
    commands:
      - cd lambda  # Change directory back to the Lambda function folder
      - zip -r lambda_function.zip .  # Create a ZIP archive of the Lambda function code
