version: 0.0
os: linux
files:
  - source: /ui/index.html
    destination: /var/www/html/
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - cd lambda  # Change directory to the Lambda function folder
      - pip install -r requirements.txt  # Install Python dependencies using pip
      - npm install  # Install JavaScript dependencies using npm (if applicable)
