version: 0.0
os: linux
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - python -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - lambda invoke --function-name lambda_handler
